sonar.projectKey=obrasci          
sonar.projectName=Obrasci CSharp Project

sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**

sonar.host.url=http://localhost:9000
sonar.login=sqp_f0145434a3509fc26cd77ab0adbf0f810c6a5841